FROM $com.sap.opensuse.python36
RUN python3.6 -m pip install numpy==1.16.4
RUN python3.6 -m pip install pandas==0.24.0
RUN python3.6 -m pip install sklearn
RUN python3.6 -m pip install papermill
RUN python3.6 -m pip install GitPython
RUN python3.6 -m pip install tornado==5.0.2
RUN python3.6 -m pip install jupyter
RUN python3.6 -m pip install git-clone
RUN python3.6 -m pip install keras
RUN python3.6 -m pip install tensorflow
RUN python3.6 -m pip install hdfs
RUN python3.6 -m pip install datetime
RUN python3.6 -m pip install mlflow







